version: '3.8'
services:
  react-laboratorio:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-http://172.16.106.19:3000/api}
        VITE_BASE_URL: ${VITE_BASE_URL:-http://172.16.106.19:3000}
    container_name: weblaboratorio-react
    ports:
      - "3001:80"
    restart: unless-stopped
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://172.16.106.19:3000/api}
      - VITE_BASE_URL=${VITE_BASE_URL:-http://172.16.106.19:3000}